version: "3.7"

services:
    front:
        build:
            context: ./front_builder_react/
            args:
                arg_port: 8080
                rest_url: "http://rest:5000"
                ws_url: "ws://socket:5000"
        logging:
            driver: none
        ports:
            - "80:8080" # http
            - "443:8080" # https
        # restart: always

    rest:
        build:
            context: ./rest_server/
            args:
                arg_port: 5000
        ports:
            - "8001:5000"
        env_file:
            - ./.env
        tty: true # bind console
        restart: always

    socket:
        build:
            context: ./websocket_server/
            args:
                arg_port: 5000
                php_url: "http://render:5000"
                tableauID: ( "627e3ed4e9f9d2f53e8b1d37" ) 
                valueID: "627e3ed4e9f9d2f53e8b1d37"
        ports:
            - "8002:5000"
        env_file:
            - ./.env
        tty: true # bind console
        # restart: always
        depends_on:
            - render

    render:
        build:
            context: ./render_server/
            args:
                arg_port: 5000
        logging:
            driver: none
        # ports:
        #     - "8003:5000"
        tty: true # bind console
        restart: always
